org: wagner96
app: user
service: workshop

frameworkVersion: "2"
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:CreateTable
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:ListStreams
          Resource: "arn:aws:dynamodb:us-east-1:*:*"
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  createContact:
    handler: create.handler
    events:
      - http:
          path: /contacts/
          method: post
  showContact:
    handler: show.handler
    events:
      - http:
          path: /contacts/{id}
          method: get
  updateContact:
    handler: update.handler
    events:
      - http:
          path: /contacts/{id}
          method: put
  listContact:
    handler: list.handler
    events:
      - http:
          path: /contacts/
          method: get
  deleteContact:
    handler: delete.handler
    events:
      - http:
          path: /contacts/{id}
          method: delete
